# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import version_pb2 as version__pb2
import configuration_pb2 as configuration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rsonardyne.api\x1a\rversion.proto\x1a\x13\x63onfiguration.proto2\xea\x02\n\x10SonardyneService\x12K\n\nGetVersion\x12\x1d.sonardyne.api.VersionRequest\x1a\x1e.sonardyne.api.VersionResponse\x12V\n\x08SetState\x12$.sonardyne.api.ConfigurationEnvelope\x1a$.sonardyne.api.ConfigurationEnvelope\x12U\n\x08GetState\x12#.sonardyne.api.ConfigurationRequest\x1a$.sonardyne.api.ConfigurationEnvelope\x12Z\n\x0bStateStream\x12#.sonardyne.api.ConfigurationRequest\x1a$.sonardyne.api.ConfigurationEnvelope0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SONARDYNESERVICE._serialized_start=69
  _SONARDYNESERVICE._serialized_end=431
# @@protoc_insertion_point(module_scope)
